<?php

/**
 * Implements hook_theme().
 */
function ossearch_simple_theme($existing, $type, $theme, $path) {

  return array(
    'ossearch_simple_results' => array(
      'template' => 'ossearch-simple-results',
      'variables' => array(
        'search_slug' => '',
        'search_form' => '',
        'keymatch_results' => '',
        'search_results' => array(),
        'search_query' => '',
        'search_pages' => '',
        'search_sort' => '',
        'ossearch' => array(),
      ),
    ),
    'ossearch_simple_keymatch_results' => array(
      'template' => 'ossearch-simple-keymatch-results',
      'variables' => [
        'results' => 'NULL'
      ]
    ),
    'ossearch_simple_result' => array(
      'template' => 'ossearch-simple-result',
      'variables' => [
        'result' => 'NULL'
      ]
    ),
    'ossearch_simple_results_control_bar' => array(
      'template' => 'ossearch-simple-results-control-bar',
      'variables' => [
        'results' => 'NULL'
      ]
    )
  );
}
